version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:  
   - OpenCover.Console.exe -register:user -target:"xunit.console.x86.exe" -targetargs:".\Test\bin\Debug\netcoreapp2.1\UnitTest.FinancialFormulas.dll -noshadow" -filter:"+[FinancialFormulas*]* -[Test*]*" -output:".\coverage.xml" -oldstyle
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
